name: "Spiced Matrix Artifact Retrieval"
description: "Retrieve artifacts from a saved GitHub Actions run"
inputs:
  repository:
    description: repository where spliced was run and artifacts saved to
    required: true
  days:
    description: number of days to check back (defaults to 2)
    required: true
    default: 2
  token:
    description: GitHub token to use GitHub API (required)
    required: true
  runid:
    description: An optional runid to filter artifact retrieval to
    required: false
  outdir:
    description: name of output directory to save to (defaults to artifacts)
    required: true
    default: artifacts

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: pip install requests
      shell: bash
    - name: Retrieve artifacts
      env:
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_DAYS: ${{ inputs.days }}
        INPUT_OUTDIR: ${{ inputs.outdir }}
      run: ${{ github.action_path }}/scripts/get_artifacts.py 
      shell: python
