
%============================================================================
% Library Facts
%============================================================================

%----------------------------------------------------------------------------
% Library: /home/vanessa/Desktop/Code/spack-vsoch/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/swig-3.0.8-ztoiu4mpglv2cv7m5tyren4lbj5hdfv4/bin/ccache-swig
%----------------------------------------------------------------------------
abi_typelocation("a","stdin","Import","Integer32","var").
abi_typelocation("a","stdin","Import","Integer8","(var+8)").
abi_typelocation("a","stdin","Import","Integer8","(var+16)").
abi_typelocation("a","stdin","Import","Integer8","(var+24)").
abi_typelocation("a","stdin","Import","Integer8","(var+32)").
abi_typelocation("a","stdin","Import","Integer8","(var+40)").
abi_typelocation("a","stdin","Import","Integer8","(var+48)").
abi_typelocation("a","stdin","Import","Integer8","(var+56)").
abi_typelocation("a","stdin","Import","Integer8","(var+64)").
abi_typelocation("a","stdin","Import","Integer8","(var+72)").
abi_typelocation("a","stdin","Import","Integer8","(var+80)").
abi_typelocation("a","stdin","Import","Integer8","(var+88)").
abi_typelocation("a","stdin","Import","Empty","(var+96)").
abi_typelocation("a","stdin","Import","Integer32","var").
abi_typelocation("a","stdin","Import","Integer8","(var+8)").
abi_typelocation("a","stdin","Import","Integer8","(var+16)").
abi_typelocation("a","stdin","Import","Integer8","(var+24)").
abi_typelocation("a","stdin","Import","Integer8","(var+32)").
abi_typelocation("a","stdin","Import","Integer8","(var+40)").
abi_typelocation("a","stdin","Import","Integer8","(var+48)").
abi_typelocation("a","stdin","Import","Integer8","(var+56)").
abi_typelocation("a","stdin","Import","Integer8","(var+64)").
abi_typelocation("a","stdin","Import","Integer8","(var+72)").
abi_typelocation("a","stdin","Import","Integer8","(var+80)").
abi_typelocation("a","stdin","Import","Integer8","(var+88)").
abi_typelocation("a","stdin","Import","Empty","(var+96)").
abi_typelocation("a","stdin","Import","Opaque","(var+104)").
abi_typelocation("a","stdin","Import","Integer32","var+112").
abi_typelocation("a","stdin","Import","Integer32","var+116").
abi_typelocation("a","stdin","Import","Integer64","var+120").
abi_typelocation("a","stdin","Import","Integer16","var+128").
abi_typelocation("a","stdin","Import","Integer8","var+130").
abi_typelocation("a","stdin","Import","Array[1:1]","var").
abi_typelocation("a","stdin","Import","Integer8","var").
abi_typelocation("a","stdin","Import","Integer64","var+144").
abi_typelocation("a","stdin","Import","Empty","(var+152)").
abi_typelocation("a","stdin","Import","Empty","(var+160)").
abi_typelocation("a","stdin","Import","Opaque","(var+168)").
abi_typelocation("a","stdin","Import","Void","(var+176)").
abi_typelocation("a","stdin","Import","Integer64","var+184").
abi_typelocation("a","stdin","Import","Integer32","var+192").
abi_typelocation("a","stdin","Import","Array[20:20]","var").
abi_typelocation("a","stdin","Import","Integer8","var").
abi_typelocation("a","stdin","Import","Integer32","var+112").
abi_typelocation("a","stdin","Import","Integer32","var+116").
abi_typelocation("a","stdin","Import","Integer64","var+120").
abi_typelocation("a","stdin","Import","Integer16","var+128").
abi_typelocation("a","stdin","Import","Integer8","var+130").
abi_typelocation("a","stdin","Import","Array[1:1]","var").
abi_typelocation("a","stdin","Import","Integer8","var").
abi_typelocation("a","stdin","Import","Integer64","var+144").
abi_typelocation("a","stdin","Import","Empty","(var+152)").
abi_typelocation("a","stdin","Import","Empty","(var+160)").
abi_typelocation("a","stdin","Import","Opaque","(var+168)").
abi_typelocation("a","stdin","Import","Void","(var+176)").
abi_typelocation("a","stdin","Import","Integer64","var+184").
abi_typelocation("a","stdin","Import","Integer32","var+192").
abi_typelocation("a","stdin","Import","Array[20:20]","var").
abi_typelocation("a","stdin","Import","Integer8","var").
abi_typelocation("a","stdout","Import","Integer32","var").
abi_typelocation("a","stdout","Import","Integer8","(var+8)").
abi_typelocation("a","stdout","Import","Integer8","(var+16)").
abi_typelocation("a","stdout","Import","Integer8","(var+24)").
abi_typelocation("a","stdout","Import","Integer8","(var+32)").
abi_typelocation("a","stdout","Import","Integer8","(var+40)").
abi_typelocation("a","stdout","Import","Integer8","(var+48)").
abi_typelocation("a","stdout","Import","Integer8","(var+56)").
abi_typelocation("a","stdout","Import","Integer8","(var+64)").
abi_typelocation("a","stdout","Import","Integer8","(var+72)").
abi_typelocation("a","stdout","Import","Integer8","(var+80)").
abi_typelocation("a","stdout","Import","Integer8","(var+88)").
abi_typelocation("a","stdout","Import","Empty","(var+96)").
abi_typelocation("a","stdout","Import","Integer32","var").
abi_typelocation("a","stdout","Import","Integer8","(var+8)").
abi_typelocation("a","stdout","Import","Integer8","(var+16)").
abi_typelocation("a","stdout","Import","Integer8","(var+24)").
abi_typelocation("a","stdout","Import","Integer8","(var+32)").
abi_typelocation("a","stdout","Import","Integer8","(var+40)").
abi_typelocation("a","stdout","Import","Integer8","(var+48)").
abi_typelocation("a","stdout","Import","Integer8","(var+56)").
abi_typelocation("a","stdout","Import","Integer8","(var+64)").
abi_typelocation("a","stdout","Import","Integer8","(var+72)").
abi_typelocation("a","stdout","Import","Integer8","(var+80)").
abi_typelocation("a","stdout","Import","Integer8","(var+88)").
abi_typelocation("a","stdout","Import","Empty","(var+96)").
abi_typelocation("a","stdout","Import","Opaque","(var+104)").
abi_typelocation("a","stdout","Import","Integer32","var+112").
abi_typelocation("a","stdout","Import","Integer32","var+116").
abi_typelocation("a","stdout","Import","Integer64","var+120").
abi_typelocation("a","stdout","Import","Integer16","var+128").
abi_typelocation("a","stdout","Import","Integer8","var+130").
abi_typelocation("a","stdout","Import","Array[1:1]","var").
abi_typelocation("a","stdout","Import","Integer8","var").
abi_typelocation("a","stdout","Import","Integer64","var+144").
abi_typelocation("a","stdout","Import","Empty","(var+152)").
abi_typelocation("a","stdout","Import","Empty","(var+160)").
abi_typelocation("a","stdout","Import","Opaque","(var+168)").
abi_typelocation("a","stdout","Import","Void","(var+176)").
abi_typelocation("a","stdout","Import","Integer64","var+184").
abi_typelocation("a","stdout","Import","Integer32","var+192").
abi_typelocation("a","stdout","Import","Array[20:20]","var").
abi_typelocation("a","stdout","Import","Integer8","var").
abi_typelocation("a","stdout","Import","Integer32","var+112").
abi_typelocation("a","stdout","Import","Integer32","var+116").
abi_typelocation("a","stdout","Import","Integer64","var+120").
abi_typelocation("a","stdout","Import","Integer16","var+128").
abi_typelocation("a","stdout","Import","Integer8","var+130").
abi_typelocation("a","stdout","Import","Array[1:1]","var").
abi_typelocation("a","stdout","Import","Integer8","var").
abi_typelocation("a","stdout","Import","Integer64","var+144").
abi_typelocation("a","stdout","Import","Empty","(var+152)").
abi_typelocation("a","stdout","Import","Empty","(var+160)").
abi_typelocation("a","stdout","Import","Opaque","(var+168)").
abi_typelocation("a","stdout","Import","Void","(var+176)").
abi_typelocation("a","stdout","Import","Integer64","var+184").
abi_typelocation("a","stdout","Import","Integer32","var+192").
abi_typelocation("a","stdout","Import","Array[20:20]","var").
abi_typelocation("a","stdout","Import","Integer8","var").
abi_typelocation("a","stderr","Import","Integer32","var").
abi_typelocation("a","stderr","Import","Integer8","(var+8)").
abi_typelocation("a","stderr","Import","Integer8","(var+16)").
abi_typelocation("a","stderr","Import","Integer8","(var+24)").
abi_typelocation("a","stderr","Import","Integer8","(var+32)").
abi_typelocation("a","stderr","Import","Integer8","(var+40)").
abi_typelocation("a","stderr","Import","Integer8","(var+48)").
abi_typelocation("a","stderr","Import","Integer8","(var+56)").
abi_typelocation("a","stderr","Import","Integer8","(var+64)").
abi_typelocation("a","stderr","Import","Integer8","(var+72)").
abi_typelocation("a","stderr","Import","Integer8","(var+80)").
abi_typelocation("a","stderr","Import","Integer8","(var+88)").
abi_typelocation("a","stderr","Import","Empty","(var+96)").
abi_typelocation("a","stderr","Import","Integer32","var").
abi_typelocation("a","stderr","Import","Integer8","(var+8)").
abi_typelocation("a","stderr","Import","Integer8","(var+16)").
abi_typelocation("a","stderr","Import","Integer8","(var+24)").
abi_typelocation("a","stderr","Import","Integer8","(var+32)").
abi_typelocation("a","stderr","Import","Integer8","(var+40)").
abi_typelocation("a","stderr","Import","Integer8","(var+48)").
abi_typelocation("a","stderr","Import","Integer8","(var+56)").
abi_typelocation("a","stderr","Import","Integer8","(var+64)").
abi_typelocation("a","stderr","Import","Integer8","(var+72)").
abi_typelocation("a","stderr","Import","Integer8","(var+80)").
abi_typelocation("a","stderr","Import","Integer8","(var+88)").
abi_typelocation("a","stderr","Import","Empty","(var+96)").
abi_typelocation("a","stderr","Import","Opaque","(var+104)").
abi_typelocation("a","stderr","Import","Integer32","var+112").
abi_typelocation("a","stderr","Import","Integer32","var+116").
abi_typelocation("a","stderr","Import","Integer64","var+120").
abi_typelocation("a","stderr","Import","Integer16","var+128").
abi_typelocation("a","stderr","Import","Integer8","var+130").
abi_typelocation("a","stderr","Import","Array[1:1]","var").
abi_typelocation("a","stderr","Import","Integer8","var").
abi_typelocation("a","stderr","Import","Integer64","var+144").
abi_typelocation("a","stderr","Import","Empty","(var+152)").
abi_typelocation("a","stderr","Import","Empty","(var+160)").
abi_typelocation("a","stderr","Import","Opaque","(var+168)").
abi_typelocation("a","stderr","Import","Void","(var+176)").
abi_typelocation("a","stderr","Import","Integer64","var+184").
abi_typelocation("a","stderr","Import","Integer32","var+192").
abi_typelocation("a","stderr","Import","Array[20:20]","var").
abi_typelocation("a","stderr","Import","Integer8","var").
abi_typelocation("a","stderr","Import","Integer32","var+112").
abi_typelocation("a","stderr","Import","Integer32","var+116").
abi_typelocation("a","stderr","Import","Integer64","var+120").
abi_typelocation("a","stderr","Import","Integer16","var+128").
abi_typelocation("a","stderr","Import","Integer8","var+130").
abi_typelocation("a","stderr","Import","Array[1:1]","var").
abi_typelocation("a","stderr","Import","Integer8","var").
abi_typelocation("a","stderr","Import","Integer64","var+144").
abi_typelocation("a","stderr","Import","Empty","(var+152)").
abi_typelocation("a","stderr","Import","Empty","(var+160)").
abi_typelocation("a","stderr","Import","Opaque","(var+168)").
abi_typelocation("a","stderr","Import","Void","(var+176)").
abi_typelocation("a","stderr","Import","Integer64","var+184").
abi_typelocation("a","stderr","Import","Integer32","var+192").
abi_typelocation("a","stderr","Import","Array[20:20]","var").
abi_typelocation("a","stderr","Import","Integer8","var").
abi_typelocation("a","sys_nerr","Import","Integer32","var").
abi_typelocation("a","sys_errlist","Import","Array","var").
abi_typelocation("a","sys_errlist","Import","Integer8","(var)").
abi_typelocation("a","_sys_nerr","Import","Integer32","var").
abi_typelocation("a","_sys_errlist","Import","Array","var").
abi_typelocation("a","_sys_errlist","Import","Integer8","(var)").
abi_typelocation("a","__environ","Import","Integer8","(var)").
abi_typelocation("a","environ","Import","Integer8","(var)").
abi_typelocation("a","optarg","Import","Integer8","(var)").
abi_typelocation("a","optind","Import","Integer32","var").
abi_typelocation("a","opterr","Import","Integer32","var").
abi_typelocation("a","optopt","Import","Integer32","var").
abi_typelocation("a","program_invocation_name","Import","Integer8","(var)").
abi_typelocation("a","program_invocation_short_name","Import","Integer8","(var)").
abi_typelocation("a","_sys_siglist","Import","Array","var").
abi_typelocation("a","_sys_siglist","Import","Integer8","(var)").
abi_typelocation("a","sys_siglist","Import","Array","var").
abi_typelocation("a","sys_siglist","Import","Integer8","(var)").
abi_typelocation("a","__tzname","Import","Array[16:2]","var").
abi_typelocation("a","__tzname","Import","Integer8","(var)").
abi_typelocation("a","__daylight","Import","Integer32","var").
abi_typelocation("a","__timezone","Import","Integer64","var").
abi_typelocation("a","tzname","Import","Array","var").
abi_typelocation("a","tzname","Import","Integer8","(var)").
abi_typelocation("a","daylight","Import","Integer32","var").
abi_typelocation("a","timezone","Import","Integer64","var").
abi_typelocation("a","getdate_err","Import","Integer32","var").
abi_typelocation("a","ccache_verbose","Import","Integer32","var").
abi_typelocation("a","cache_dir","Export","Integer8","(var)").
abi_typelocation("a","cache_logfile","Export","Integer8","(var)").
abi_typelocation("a","stats_file","Export","Integer8","(var)").
abi_typelocation("a","strcat","Import","Integer8","()").
abi_typelocation("a","strcat","Import","Integer8","()").
abi_typelocation("a","strcat","Export","Integer8","(%rax)").
abi_typelocation("a","strncpy","Import","Integer8","()").
abi_typelocation("a","strncpy","Import","Integer8","()").
abi_typelocation("a","strncpy","Import","Integer64","%rdi").
abi_typelocation("a","strncpy","Export","Integer8","(%rax)").
abi_typelocation("a","open","Both","Integer8","(%rdi)").
abi_typelocation("a","open","Import","Integer32","%rsi").
abi_typelocation("a","open","Export","Integer32","%rax").
abi_typelocation("a","gethostname","Both","Integer8","(%rdi)").
abi_typelocation("a","gethostname","Import","Integer64","%rsi").
abi_typelocation("a","gethostname","Export","Integer32","%rax").
abi_typelocation("a","fgets","Import","Integer8","()").
abi_typelocation("a","fgets","Import","Integer32","%rdi").
abi_typelocation("a","fgets","Import","Integer32","()").
abi_typelocation("a","fgets","Import","Integer8","(()+8)").
abi_typelocation("a","fgets","Import","Integer8","(()+16)").
abi_typelocation("a","fgets","Import","Integer8","(()+24)").
abi_typelocation("a","fgets","Import","Integer8","(()+32)").
abi_typelocation("a","fgets","Import","Integer8","(()+40)").
abi_typelocation("a","fgets","Import","Integer8","(()+48)").
abi_typelocation("a","fgets","Import","Integer8","(()+56)").
abi_typelocation("a","fgets","Import","Integer8","(()+64)").
abi_typelocation("a","fgets","Import","Integer8","(()+72)").
abi_typelocation("a","fgets","Import","Integer8","(()+80)").
abi_typelocation("a","fgets","Import","Integer8","(()+88)").
abi_typelocation("a","fgets","Import","Empty","(()+96)").
abi_typelocation("a","fgets","Import","Integer32","(()+104)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+8)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+16)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+24)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+32)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+40)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+48)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+56)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+64)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+72)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+80)").
abi_typelocation("a","fgets","Import","Integer8","((()+104)+88)").
abi_typelocation("a","fgets","Import","Empty","((()+104)+96)").
abi_typelocation("a","fgets","Import","Opaque","((()+104)+104)").
abi_typelocation("a","fgets","Import","Integer32","(()+104)+112").
abi_typelocation("a","fgets","Import","Integer32","(()+104)+116").
abi_typelocation("a","fgets","Import","Integer64","(()+104)+120").
abi_typelocation("a","fgets","Import","Integer16","(()+104)+128").
abi_typelocation("a","fgets","Import","Integer8","(()+104)+130").
abi_typelocation("a","fgets","Import","Array[1:1]","(()+104)+131").
abi_typelocation("a","fgets","Import","Integer8","(()+104)+131").
abi_typelocation("a","fgets","Import","Integer64","(()+104)+144").
abi_typelocation("a","fgets","Import","Empty","((()+104)+152)").
abi_typelocation("a","fgets","Import","Empty","((()+104)+160)").
abi_typelocation("a","fgets","Import","Opaque","((()+104)+168)").
abi_typelocation("a","fgets","Import","Void","((()+104)+176)").
abi_typelocation("a","fgets","Import","Integer64","(()+104)+184").
abi_typelocation("a","fgets","Import","Integer32","(()+104)+192").
abi_typelocation("a","fgets","Import","Array[20:20]","(()+104)+196").
abi_typelocation("a","fgets","Import","Integer8","(()+104)+196").
abi_typelocation("a","fgets","Import","Integer32","()+112").
abi_typelocation("a","fgets","Import","Integer32","()+116").
abi_typelocation("a","fgets","Import","Integer64","()+120").
abi_typelocation("a","fgets","Import","Integer16","()+128").
abi_typelocation("a","fgets","Import","Integer8","()+130").
abi_typelocation("a","fgets","Import","Array[1:1]","()+131").
abi_typelocation("a","fgets","Import","Integer8","()+131").
abi_typelocation("a","fgets","Import","Integer64","()+144").
abi_typelocation("a","fgets","Import","Empty","(()+152)").
abi_typelocation("a","fgets","Import","Empty","(()+160)").
abi_typelocation("a","fgets","Import","Opaque","(()+168)").
abi_typelocation("a","fgets","Import","Void","(()+176)").
abi_typelocation("a","fgets","Import","Integer64","()+184").
abi_typelocation("a","fgets","Import","Integer32","()+192").
abi_typelocation("a","fgets","Import","Array[20:20]","()+196").
abi_typelocation("a","fgets","Import","Integer8","()+196").
abi_typelocation("a","fgets","Export","Integer8","(%rax)").
abi_typelocation("a","__errno_location","Export","Void","none").
abi_typelocation("a","strtol","Export","Void","none").
abi_typelocation("a","umask","Export","Void","none").
abi_typelocation("a","dup","Export","Void","none").
abi_typelocation("a","putenv","Export","Void","none").
abi_typelocation("a","strcmp","Export","Void","none").
abi_typelocation("a","getenv","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","strchr","Export","Void","none").
abi_typelocation("a","perror","Export","Void","none").
abi_typelocation("a","exit","Export","Void","none").
abi_typelocation("a","strstr","Export","Void","none").
abi_typelocation("a","__xstat","Export","Void","none").
abi_typelocation("a","strncmp","Export","Void","none").
abi_typelocation("a","unlink","Export","Void","none").
abi_typelocation("a","puts","Export","Void","none").
abi_typelocation("a","__printf_chk","Export","Void","none").
abi_typelocation("a","getopt","Export","Void","none").
abi_typelocation("a","__fprintf_chk","Export","Void","none").
abi_typelocation("a","strlen","Export","Void","none").
abi_typelocation("a","strerror","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","strrchr","Export","Void","none").
abi_typelocation("a","strncpy","Export","Void","none").
abi_typelocation("a","strcat","Export","Void","none").
abi_typelocation("a","__sprintf_chk","Export","Void","none").
abi_typelocation("a","__strcpy_chk","Export","Void","none").
abi_typelocation("a","fgets","Export","Void","none").
abi_typelocation("a","fclose","Export","Void","none").
abi_typelocation("a","fopen","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","gethostname","Export","Void","none").
abi_typelocation("a","__asprintf_chk","Export","Void","none").
abi_typelocation("a","getpid","Export","Void","none").
abi_typelocation("a","execv","Export","Void","none").
abi_typelocation("a","memset","Import","Integer64","%rdi").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","__memcpy_chk","Export","Void","none").
abi_typelocation("a","memcpy","Export","Void","none").
abi_typelocation("a","__sprintf_chk","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","read","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","strlen","Export","Void","none").
abi_typelocation("a","open","Import","Integer8","()").
abi_typelocation("a","strcmp","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","__lxstat","Export","Void","none").
abi_typelocation("a","__xstat","Export","Void","none").
abi_typelocation("a","access","Export","Void","none").
abi_typelocation("a","getenv","Export","Void","none").
abi_typelocation("a","strtok","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","unlink","Export","Void","none").
abi_typelocation("a","dup2","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","execv","Export","Void","none").
abi_typelocation("a","exit","Export","Void","none").
abi_typelocation("a","fork","Export","Void","none").
abi_typelocation("a","waitpid","Export","Void","none").
abi_typelocation("a","__printf_chk","Export","Void","none").
abi_typelocation("a","putchar","Export","Void","none").
abi_typelocation("a","fflush","Export","Void","none").
abi_typelocation("a","dirname","Import","Integer8","()").
abi_typelocation("a","dirname","Export","Integer8","()").
abi_typelocation("a","getcwd","Import","Integer8","()").
abi_typelocation("a","getcwd","Export","Integer8","()").
abi_typelocation("a","getuid","Export","Void","none").
abi_typelocation("a","getpwuid","Export","Void","none").
abi_typelocation("a","getenv","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","malloc","Export","Void","none").
abi_typelocation("a","getcwd","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","__errno_location","Export","Void","none").
abi_typelocation("a","__realpath_chk","Export","Void","none").
abi_typelocation("a","strdup","Export","Void","none").
abi_typelocation("a","strtod","Export","Void","none").
abi_typelocation("a","strlen","Export","Void","none").
abi_typelocation("a","__printf_chk","Export","Void","none").
abi_typelocation("a","fcntl","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","strrchr","Export","Void","none").
abi_typelocation("a","__lxstat","Export","Void","none").
abi_typelocation("a","perror","Export","Void","none").
abi_typelocation("a","opendir","Export","Void","none").
abi_typelocation("a","readdir","Export","Void","none").
abi_typelocation("a","closedir","Export","Void","none").
abi_typelocation("a","realloc","Export","Void","none").
abi_typelocation("a","__vasprintf_chk","Export","Void","none").
abi_typelocation("a","__xstat","Export","Void","none").
abi_typelocation("a","fopen","Export","Void","none").
abi_typelocation("a","fwrite","Export","Void","none").
abi_typelocation("a","fclose","Export","Void","none").
abi_typelocation("a","mkdir","Export","Void","none").
abi_typelocation("a","utimes","Export","Void","none").
abi_typelocation("a","unlink","Export","Void","none").
abi_typelocation("a","link","Export","Void","none").
abi_typelocation("a","strerror","Export","Void","none").
abi_typelocation("a","fgetc","Export","Void","none").
abi_typelocation("a","__fxstat","Export","Void","none").
abi_typelocation("a","gzdopen","Export","Void","none").
abi_typelocation("a","mkstemp","Export","Void","none").
abi_typelocation("a","write","Export","Void","none").
abi_typelocation("a","gzread","Export","Void","none").
abi_typelocation("a","gzwrite","Export","Void","none").
abi_typelocation("a","gzclose","Export","Void","none").
abi_typelocation("a","umask","Export","Void","none").
abi_typelocation("a","fchmod","Export","Void","none").
abi_typelocation("a","rename","Export","Void","none").
abi_typelocation("a","dup","Export","Void","none").
abi_typelocation("a","exit","Export","Void","none").
abi_typelocation("a","__vfprintf_chk","Export","Void","none").
abi_typelocation("a","fflush","Export","Void","none").
abi_typelocation("a","memmove","Export","Void","none").
abi_typelocation("a","strlen","Export","Void","none").
abi_typelocation("a","strncmp","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","unlink","Export","Void","none").
abi_typelocation("a","__printf_chk","Export","Void","none").
abi_typelocation("a","putchar","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","dirname","Export","Void","none").
abi_typelocation("a","getenv","Export","Void","none").
abi_typelocation("a","read","Export","Void","none").
abi_typelocation("a","strtol","Export","Void","none").
abi_typelocation("a","__snprintf_chk","Export","Void","none").
abi_typelocation("a","snprintf","Export","Void","none").
abi_typelocation("a","lseek","Export","Void","none").
abi_typelocation("a","write","Export","Void","none").
abi_typelocation("a","free","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
abi_typelocation("a","__fprintf_chk","Export","Void","none").
abi_typelocation("a","qsort","Export","Void","none").
abi_typelocation("a","unlink","Export","Void","none").
abi_typelocation("a","__errno_location","Export","Void","none").
abi_typelocation("a","strerror","Export","Void","none").
abi_typelocation("a","strcmp","Export","Void","none").
abi_typelocation("a","open","Export","Void","none").
abi_typelocation("a","__fxstat","Export","Void","none").
abi_typelocation("a","memset","Export","Void","none").
abi_typelocation("a","__ctype_b_loc","Export","Void","none").
abi_typelocation("a","strlen","Export","Void","none").
abi_typelocation("a","memcmp","Export","Void","none").
abi_typelocation("a","mmap","Export","Void","none").
abi_typelocation("a","close","Export","Void","none").
abi_typelocation("a","munmap","Export","Void","none").
abi_typelocation("a","__stack_chk_fail","Export","Void","none").
