name: Test Spliced Action
on:
  pull_request: []
 
jobs:
  install-spliced:
    runs-on: ubuntu-latest
    name: Install Spliced
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Spliced
        uses: ./actions/install

  generate-matrix:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    name: Generate Spliced Matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Spliced
        uses: ./actions/install
      - name: Generate Matrix
        uses: ./actions/matrix
        id: matrix
        with:
          yaml: ./spliced/curl.yaml

      - name: Show result
        env:
           matrix: ${{ steps.matrix.outputs.matrix }}
        run: echo ${matrix}
